export const findCompanyArr: findCompanydataModel[] = [
    {
        id: 1,
        title: 'Adr International Limited',
        address: '02018150 - Chiltern House, Station Road, Henley-On-Thames, Ox...',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Sole Proprietorship",
        postcode: "13138431",
        address_line_1: "02018150 - Chiltern House",
        address_line_2: "Station Road, Henley-On-Thames, Ox",
        city: "Torrento",
        incorporate_activity: "09/2022",
        business_activity: "Torrento",
        country: 'India',
    },
    {
        id: 2,
        title: 'Adraa Property Group Limited',
        address: '02018150 - Chiltern House, Station Road, Henley-On-Thames, Ox...',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Sole Proprietorship",
        postcode: "KA3 1BD",
        address_line_1: "02018151 - Riverside House",
        address_line_2: "River Street, Henley-On-Thames, Ox",
        city: "Streamsville",
        incorporate_activity: "09/2023",
        business_activity: "Streamsville",
        country: 'Russia',
    },
    {
        id: 3,
        title: 'Adr International Limited',
        address: '02018153 - Valley House, High Street, Oxford',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Partnership",
        postcode: "KA5 1BD",
        address_line_1: "02018153 - Valley House",
        address_line_2: "High Street, Oxford",
        city: "Oxford",
        incorporate_activity: "05/2022",
        business_activity: "Oxford",
        country: 'India',
    },
    {
        id: 4,
        title: 'Adr National Limited',
        address: '020181662 - Chiltern House, Station Road, Henley-On-Thames, Ox...',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Sole Proprietorship",
        postcode: "KD5 1BD",
        address_line_1: "020181662 - Chiltern House",
        address_line_2: "Station Road, Henley-On-Thames, Ox",
        city: "Henley-On-Thames",
        incorporate_activity: "09/2021",
        business_activity: "Henley-On-Thames",
        country: 'India',
    },
    {
        id: 5,
        title: 'ABC Corporation',
        address: '123 Main Street, Springfield, IL 62701',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Partnership",
        postcode: "KE9 1BD",
        address_line_1: "123 Main Street",
        address_line_2: "Springfield, IL",
        city: "Springfield",
        incorporate_activity: "01/2022",
        business_activity: "Springfield",
        country: 'U.S.',
    },
    {
        id: 6,
        title: 'XYZ Industries, Inc.',
        address: '456 Oak Avenue, New York, NY 10001',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Limited Liability Company",
        postcode: "10001",
        address_line_1: "456 Oak Avenue",
        address_line_2: "New York, NY",
        city: "New York",
        incorporate_activity: "02/2023",
        business_activity: "New York",
        country: 'U.S.',
    },
    {
        id: 7,
        title: 'Sunshine Enterprises',
        address: '789 Beach Road, Miami, FL 33101',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Company",
        postcode: "33101",
        address_line_1: "789 Beach Road",
        address_line_2: "Miami, FL",
        city: "Miami",
        incorporate_activity: "10/2022",
        business_activity: "Miami",
        country: 'U.S.',
    },
    {
        id: 8,
        title: 'Tech Innovators Ltd.',
        address: '101 Tech Park, San Francisco, CA 94101',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Company",
        postcode: "94101",
        address_line_1: "101 Tech Park",
        address_line_2: "San Francisco, CA",
        city: "San Francisco",
        incorporate_activity: "03/2022",
        business_activity: "San Francisco",
        country: 'U.S.',
    },
    {
        id: 9,
        title: 'EcoTech Solutions, Inc.',
        address: '456 Green Street, Seattle, WA 98101',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Limited Liability Company",
        postcode: "98101",
        address_line_1: "456 Green Street",
        address_line_2: "Seattle, WA",
        city: "Seattle",
        incorporate_activity: "04/2022",
        business_activity: "Seattle",
        country: 'U.S.',
    },
    {
        id: 10,
        title: 'Global Services Group',
        address: '789 World Avenue, London, UK SW1A 1AA',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Partnership",
        postcode: "SW1A 1AA",
        address_line_1: "789 World Avenue",
        address_line_2: "London, UK",
        city: "London",
        incorporate_activity: "09/2021",
        business_activity: "London",
        country: 'U.S.',
    },
    {
        id: 11,
        title: "Nature's Bounty Co.",
        address: '123 Forest Lane, Denver, CO 80201',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Registered Company",
        postcode: "80201",
        address_line_1: "123 Forest Lane",
        address_line_2: "Denver, CO",
        city: "Denver",
        incorporate_activity: "03/2022",
        business_activity: "Denver",
        country: 'U.S.',
    },
    {
        id: 12,
        title: 'InnovateTech Corporation',
        address: '101 Innovation Road, Austin, TX 78701',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Registered Company",
        postcode: "78701",
        address_line_1: "101 Innovation Road",
        address_line_2: "Austin, TX",
        city: "Austin",
        incorporate_activity: "09/2022",
        business_activity: "Austin",
        country: 'U.S.',
    },
    {
        id: 13,
        title: 'Sunrise Tech Solutions',
        address: '789 Sunrise Avenue, Los Angeles, CA 90001',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Partnership",
        postcode: "90001",
        address_line_1: "789 Sunrise Avenue",
        address_line_2: "Los Angeles, CA",
        city: "Los Angeles",
        incorporate_activity: "09/2022",
        business_activity: "Los Angeles",
        country: 'Australia',
    },
    {
        id: 14,
        title: 'Northern Ventures, LLC',
        address: '456 North Street, Chicago, IL 60601',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Partnership",
        postcode: "60601",
        address_line_1: "456 North Street",
        address_line_2: "Chicago, IL",
        city: "Chicago",
        incorporate_activity: "09/2022",
        business_activity: "Chicago",
        country: 'Canada',
    },
    {
        id: 15,
        title: 'Golden Gate Industries',
        address: '123 Golden Gate Road, San Francisco, CA 94101',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Registered Company",
        postcode: "94101",
        address_line_1: "123 Golden Gate Road",
        address_line_2: "San Francisco, CA",
        city: "San Francisco",
        incorporate_activity: "09/2022",
        business_activity: "San Francisco",
        country: 'Canada',
    },
    {
        id: 16,
        title: 'Infinite Innovations, Inc.',
        address: '101 Infinite Lane, New York, NY 10001',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Registered Company",
        postcode: "10001",
        address_line_1: "101 Infinite Lane",
        address_line_2: "New York, NY",
        city: "New York",
        incorporate_activity: "09/2020",
        business_activity: "New York",
        country: 'United Kingdom',
    },
    {
        id: 17,
        title: 'Tech Innovators, LLC',
        address: '456 Tech Street, San Jose, CA 95101',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Limited Liability Partnership",
        postcode: "95101",
        address_line_1: "456 Tech Street",
        address_line_2: "San Jose, CA",
        city: "San Jose",
        incorporate_activity: "09/2022",
        business_activity: "San Jose",
        country: 'United Kingdom',
    },
    {
        id: 18,
        title: 'Global Tech Solutions, Inc.',
        address: '789 Innovation Avenue, Austin, TX 78701',
        company_name: "Corporation",
        company_number: "Corporation",
        business_type: "Partnership",
        postcode: "78701",
        address_line_1: "789 Innovation Avenue",
        address_line_2: "Austin, TX",
        city: "Austin",
        incorporate_activity: "09/2021",
        business_activity: "Austin",
        country: 'France',
    },
    {
        id: 19,
        title: 'Smart Ventures Group',
        address: '123 Smart Road, Seattle, WA 98101',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Sole Proprietorship",
        postcode: "98101",
        address_line_1: "123 Smart Road",
        address_line_2: "Seattle, WA",
        city: "Seattle",
        incorporate_activity: "09/2019",
        business_activity: "Seattle",
        country: 'Germany',
    },
    {
        id: 20,
        title: 'Innovate Systems, Ltd.',
        address: '101 Innovation Park, London, UK SW1A 1AA',
        company_name: "Limited Liability Company",
        company_number: "Limited Liability Company",
        business_type: "Sole Proprietorship",
        postcode: "SW1A 1AA",
        address_line_1: "101 Innovation Park",
        address_line_2: "London, UK",
        city: "London",
        incorporate_activity: "09/2022",
        business_activity: "London",
        country: 'Japan',
    },
];


interface findCompanydataModel {
    id: number;
    title: string;
    address: string;
    company_name: string;
    company_number: string;
    business_type: string;
    postcode: string;
    address_line_1: string;
    address_line_2: string;
    city: string;
    incorporate_activity: string;
    business_activity: string;
    country: string;
} 