import { v4 as uuid } from 'uuid';
export const AUTHORIZED_SIGNATORY = [
    {
        profilePic: null,
        firstName: 'Laura',
        lastName: 'Hollend',
        altProfileText: 'LH',
        id: uuid(),
        verificationStatus: 'Please verify',
        city: 'Torrento',
        addressLine1: '02018150 - Chiltern House',
        addressLine2: 'Station Road, Henley-On-Thames, Ox',
        role: 'Shareholder',
        country: 'India',
        dateOfBirth: '2023-11-07T18:30:00.000Z',
        middleName: 'dfgfdgfd',
        mobilenumber: '4862665161',
        email: 'dfgfdgfd@gmail.com',
        countryLocation: '+91',
        isAccountHolder: false
    },
    {
        profilePic: null,
        firstName: 'James',
        lastName: 'Smith',
        altProfileText: 'JS',
        id: uuid(),
        verificationStatus: 'Please verify',
        city: 'Torrento',
        addressLine1: '02018150 - Chiltern House',
        addressLine2: 'Station Road, Henley-On-Thames, Ox',
        role: 'Shareholder',
        country: 'India',
        dateOfBirth: '2023-11-07T18:30:00.000Z',
        middleName: 'dfgfdgfd',
        mobilenumber: '4862665161',
        email: 'dfgfdgfd@gmail.com',
        countryLocation: '+91',
        isAccountHolder: false
    },
    {
        profilePic: null,
        firstName: 'James',
        lastName: 'Ross',
        altProfileText: 'JS',
        id: uuid(),
        verificationStatus: 'Please verify',
        city: 'Torrento',
        addressLine1: '02018150 - Chiltern House',
        addressLine2: 'Station Road, Henley-On-Thames, Ox',
        role: 'Shareholder',
        country: 'India',
        dateOfBirth: '2023-11-07T18:30:00.000Z',
        middleName: 'dfgfdgfd',
        mobilenumber: '4862665161',
        email: 'dfgfdgfd@gmail.com',
        countryLocation: '+91',
        isAccountHolder: false
    },
];
